### ISSUE TITLE
Continuous data time axis not editable

### ISSUE THREAD

**Issue by kajal5888** [esi-neuroscience/syncopy#483] opened 2023-04-20 09:49 UTC
**Is your feature request related to a problem? Please elaborate.**
The time axis need to be editable so that we can realign the data to the target stimulus or reaction time. 

Describe the bug
Creating a dataset using snp.AnalogData and not able to change time information.

To Reproduce

DataArray = np.random.random((100,5))
DesiredChannelNames = ['V1Channel1','V1Channel2','V1Channel3','V4hannel1','V4Channel2']
DummyData = snp.AnalogData(data=DataArray, samplerate=25, channel=DesiredChannelNames)
DummyData.time = np.arange(100)/100

SyNCoPy encountered an error in 

<stdin>, line 1 in <module>

AttributeError: can't set attribute

Expected behavior
The time axis needs to be editable

**Comment by tensionhead** [comment] 2023-04-20 14:21
This is a feature not a bug! The `time` property gets computed from the sampleinfo, samplerate and offset. If you want to move (translation) the time axis, changing the offset (for example via `redefinetrial`) is probably your best option. Closing this, freely setting the time property is not something we want to allow.

**Closed** 2023-04-20 14:22 UTC
Labels: Feature Request
