### ISSUE TITLE
Catch performance degradations via performance testing

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#361] opened 2022-10-13 12:55 UTC
We now have already one case, where most likely some at first seemingly unrelated changes slowed down `SpikeData` I/O by a huge amount:  #360 

Given the complexity/connectedness of the Syncopy code-base, and the sensitive matter of performance in light of big data and parallelism, it would be really great if could test *performance*. The simplest I could think of would be  some timing/benchmarking it takes to perform at least some operations (like saving and loading), however then we would also need a deterministic testing environment. To start, it's probably best to experiment with a completely new CI pipeline as it can be a [fairly complex topic](https://testfully.io/blog/performance-testing/)

**Comment by tensionhead** [comment] 2023-04-18 12:32
Airspeed velocity looks promising to at least catch single machine performance: https://asv.readthedocs.io/en/stable/

**Comment by dfsp-spirit** [comment] 2023-06-01 08:15
We decided for asv, I am closing this as it has now become a duplicate of the more specific issue #494

**Closed** 2023-06-01 13:55 UTC
Labels: Design, Explore, Tests
